In [57]:
import numpy as np
from math import sqrt

In [2]:
a= input("enter the number of rows and columns ")

enter the number of rows and columns 4 2


In [3]:
b = a.split()

In [4]:
c=np.random.random((int(b[0]),int(b[1])))

In [20]:
np.savetxt('random.txt',c,fmt='%f')

In [23]:
y = np.loadtxt('random.txt')

In [25]:
type(y)

numpy.ndarray

In [27]:
y = y *6

In [28]:
y

array([[5.937852, 5.279808],
       [4.114842, 3.823278],
       [2.505282, 4.675014],
       [1.456428, 1.287564]])

In [29]:
np.savetxt("random1.txt",y,fmt='%f')

In [45]:
b = input("enter the number of rows and columns ")

enter the number of rows and columns 8 16


In [48]:
b = b.split()

In [50]:
c = max(int(b[0]), int(b[1]))

In [51]:
c

16

In [64]:
i = 0
pair=[]

In [65]:
for i in range(1,int(sqrt(c))+1):
    if c%i ==0:
        pair.append(i)

In [74]:
pair
matr = []

In [75]:
for i in pair:
    matr.append(np.zeros((i,int(c/i))))

In [77]:
matr

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])]