In [5]:
import numpy as np
import scipy as sp
#import matplotllib as mt

In [7]:
for i in dir(np):
    if 'arr' in i:
        print(i)

array
array2string
array_equal
array_equiv
array_repr
array_split
array_str
asanyarray
asarray
asarray_chkfinite
ascontiguousarray
asfarray
asfortranarray
broadcast_arrays
chararray
compare_chararrays
get_array_wrap
ndarray
numarray
recarray


In [8]:
a = np.array([2,3,9,7])

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [12]:
a.shape

(4,)

In [18]:
a1 = np.array([[2,4],[3,9],[5,7]])

In [19]:
a1.shape

(3, 2)

In [22]:
a3 = np.array([[2,4,5],[3,6,7],[2,3,4]])

In [23]:
a3.shape

(3, 3)

In [35]:
#storage mechanism of array 
a3[1][2]
a3[0:2,1:3]

array([[4, 5],
       [6, 7]])

In [36]:
a3[1,1]

6

In [37]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
x = np.full((4,2),3)

In [41]:
y = np.full((4,2),5)

In [53]:
x = x/3 #there can be operations like add - * /  

In [55]:
x

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [56]:
x = x+y

In [58]:
np.add(x,y)

array([[12., 12.],
       [12., 12.],
       [12., 12.],
       [12., 12.]])

# assignment
1. take dimensions from users and create a numpy array with random numbers as element
2. same pg but you have to print output in screen and save in a file as well
3. read numpy data from a file as done in 2 program and muptiple by 6 and then print it back
4. take any rows and columns by user and print all possible matrix with element 0.(see it 1 time)