In [60]:
import sys

In [62]:
!{sys.executable} -m pip install matplotlib

  Using cached https://files.pythonhosted.org/packages/4e/11/06958a2b895a3853206dea1fb2a5b11bf044f626f90745987612af9c8f2c/matplotlib-3.1.2-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl
You should consider upgrading via the 'pip install --upgrade pip' command.


In [59]:
import numpy as np
import scipy as sp
import matplotllib as mt

ModuleNotFoundError: No module named 'matplotllib'

In [7]:
for i in dir(np):
    if 'arr' in i:
        print(i)

array
array2string
array_equal
array_equiv
array_repr
array_split
array_str
asanyarray
asarray
asarray_chkfinite
ascontiguousarray
asfarray
asfortranarray
broadcast_arrays
chararray
compare_chararrays
get_array_wrap
ndarray
numarray
recarray


In [8]:
a = np.array([2,3,9,7])

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [12]:
a.shape

(4,)

In [18]:
a1 = np.array([[2,4],[3,9],[5,7]])

In [19]:
a1.shape

(3, 2)

In [22]:
a3 = np.array([[2,4,5],[3,6,7],[2,3,4]])

In [23]:
a3.shape

(3, 3)

In [35]:
#storage mechanism of array 
a3[1][2]
a3[0:2,1:3]

array([[4, 5],
       [6, 7]])

In [36]:
a3[1,1]

6

In [37]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
x = np.full((4,2),3)

In [41]:
y = np.full((4,2),5)

In [53]:
x = x/3 #there can be operations like add - * /  

In [55]:
x

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [56]:
x = x+y

In [58]:
np.add(x,y)

array([[12., 12.],
       [12., 12.],
       [12., 12.],
       [12., 12.]])

# assignment
1. take dimensions from users and create a numpy array with random numbers as element
2. same pg but you have to print output in screen and save in a file as well
3. read numpy data from a file as done in 2 program and muptiple by 6 and then print it back
4. take any rows and columns by user and print all possible matrix with element 0.(see it 1 time)